Import('qt_env')

env = qt_env.Clone()

env.AppendUnique(CPPDEFINES = [
    'INSTALLERNCC_LIBRARY',
    # boost uses things MS C++ is mldly unhappy about.
    '_SCL_SECURE_NO_WARNINGS'
])

env.AppendUnique(CPPPATH = [
    '${BOOSTPATH}'
])

env.AppendUnique(LIBS = [
    'shell32',
    'user32',
    'Version'
])

lib = env.SharedLibrary('installerNCC', env.Glob('*.cpp'))
env.InstallModule(lib)

res = env['QT_USED_MODULES']
Return('res')
