Import('qt_env')

env = qt_env.Clone()

modules = [
    'Core',
    'Gui'
]

if env['QT_MAJOR_VERSION'] > 4:
    modules += [ 'Widgets' ]

env.EnableQt4Modules(['Qt' + n for n in modules],
                     debug = env['CONFIG'] == 'debug')

env.AppendUnique(CPPDEFINES = [ 'INSTALLERNCC_LIBRARY' ])

env.RequireLibraries('uibase')

env.AppendUnique(CPPPATH = [
    '${BOOSTPATH}'
])

env.AppendUnique(LIBS = [
    'shell32',
    'user32',
    'Version'
])

lib = env.SharedLibrary('installerNCC', env.Glob('*.cpp'))
env.InstallPlugin(lib)
